apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:3CIBY1p60ZVz2SA3t4Ciks765Yp+y33umm5z07ZHot8AhG3Is9b8xH48qC7+iq4F4lpxk/LI107YrnEbhTeO,iv:6UQtOT0/1se1qcg1dNWd+MEFptyoGlq8sM4fDP5PE+A=,tag:bdfLOObLK4YNegq3n4roAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpwqy60dz36rawn8kauf7kyamnkhyywnvem097p7kfhrp429g4qfm5yly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWHd4S3huTFI1T2xMUEhB
            SXJxZ0V0VUtlM3hUTXRkV3lEL0orUVhVZFF3ClFiT1V1eDF3aEFsYVpyU2toV09X
            aldwTGJnTDl5d1FEbjVTRWlzNldKU2cKLS0tIGN5Y0J1L1FLMzJCWWdzT3JCYWVB
            aExBTzZQTlh3aitoaXpUcG94cU5DaTQKub87NmGDN1xjYkCwOb6VayC62If2Biq2
            U4DzJ1qlxPZldIx++fK1VgFUAl+boRFhq249iX19TQ7c/HgFXEByag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T15:46:44Z"
    mac: ENC[AES256_GCM,data:ocfpMB3UT5Q7e85NQ/RUhvW0vwnBJWox8xETw8xk0zg1bOtkmfmS/lcLGAlUTLUbffcKu5AsNEdrbf/y7uLMo6LlyG46uo81icGWIW+R12iASUtWb572yQObpCIHK14MBi7djFfon8qsDRtlirWW9TTQTI7gPsGfZ953ZJtpqM4=,iv:yWCWo+RCnJ31wKj+6EvaupD6cljFuoGNQpLtvI4HEpg=,tag:zXJQ/0PtrGmEhEwGxQ73rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
