apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ""
    SECRET_ACME_EMAIL: ""
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpwqy60dz36rawn8kauf7kyamnkhyywnvem097p7kfhrp429g4qfm5yly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M0VWcVY3V09vUnVVMktM
            cFZZNlp3NHJnVTgyZzd5YlQwYm5lZWltaVFRCk81UG8yci85T0ExS0tlNUJscU5k
            ZEtMaGRmWDQxcHNTaGF1NjlUQjhBajQKLS0tIE5uM1pNdmFmb05JaVpFaFMzb0tP
            SXZyL04wTnFOdWx4dG5xWGhXRk1haEEKwFQYPGarfLhEDi2rHVuCRk1ZIgl2XjXH
            W+2SxudjWN2rxA9pxvk8uJotsjckIzaqHQKwsR+ogoJu9Gm/4RjECw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T15:46:44Z"
    mac: ENC[AES256_GCM,data:MMr7QXiJkq+XCP/+FQbsXaFKF767pmKswZJb/flPs1+qTnp1q6uOGM3MoCzRNj7pjNwjw0A+7eVKUukUq+SPNiILOrYEnyfteo13EQZ3hX5jczW9ksVn/pQW6QSAnqMaYBbgVg5o568DQYjZbJJ84A3wxFp4YpyTYdfJfyWfXp0=,iv:O0m1DemS5/b2o6Jk8V62p9N1TgDMe1PdInRzMwXrbmQ=,tag:12Abpw4kFmh4/X42ZtCMUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
