apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OwVgqLawQ/+jytvpw3JRLYnQhxuGsbUG+RTPY6gnRjI=,iv:savsW13xh+tVDzfw2c8iaKSPC+LSgUvm6sHwPSsQusQ=,tag:KvtJM+iF5Y7QgLKAeYhUFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpwqy60dz36rawn8kauf7kyamnkhyywnvem097p7kfhrp429g4qfm5yly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUTVhc1kwc3czMXNwU3Vh
            dFVDbk9HbHJLL205NjdSSmUzSlFRZmFpZW1NCmthZEoxRlB2MHU2ZFJ6aU8rNnNQ
            dnpqSjZ6VTN5TkR2RlhqRDhucHgxdmcKLS0tIERLbDBpN2xwbXdtd3A1SlBlb1NL
            VjdHRm9vNUQ1UkhlODVvZGVTdVg5b1kKEPAtHZpQiC2/V5TLeun2XEDdjNhX5MNq
            NOcYJAtBZizgQILj5ULaIwccJmgTnM3Vg8tZ2a078uSSHL1Op3MJtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T17:48:20Z"
    mac: ENC[AES256_GCM,data:2gsG17iblmmvZCi31umyd/uC9c8cNACPU8trupi6kFy53bb00xcdrzwuq4x96xrJC4LvyHdfz34F9GidSpffdW4wHfs/KQfLQi6uNCLvieMCtiWBMKJxrUGyi8vByAbAFd2aFkEd1FP/bGU/8y+1l9K3WUEiov7x9hAjCrFOu4I=,iv:/XpYnhjfixE/taIM2DymfT6yxUHANUasn8eXJCeYA4k=,tag:hPCxRulwygxm04luLEHKYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
