apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rcpwqy60dz36rawn8kauf7kyamnkhyywnvem097p7kfhrp429g4qfm5yly
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSjRZOWs5eW42OUJtVWIx
            dldWMFRxdCsvLzJlSnlya09SWHBPR2NtY21VCnptR3dpNkZnSUwvT0hBNjkxYVUr
            M0UrUlZsandFNUF2UFhPWVZ4WS9SZzQKLS0tIFpaQTQraUhxbFVhazNIRGlTYlpG
            MjZTZFpqMUlCVVNxNGZVcXYvRi81a1EKxquQfCxCmt7CzIUstWoOr0V6/chsGlXM
            N804w+798KUeqGR4uGdddhQVjEJiSiNXfAhfVAYiZ1vkZs5CM/TOug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-10T15:32:20Z"
    mac: ENC[AES256_GCM,data:Mx7FeTgrN9n5TXoqR2QN3nUZvVVodAHXkIEZBdzDhVd1dbremC7D3yitjJ6yAVEy2XRwq7hUWCIrRT7UD5kyXHmqIKixJTSVMe5btXlPIDkFlRYcN8L4XNJ3wiD6EJ08Jb26cNqj0OmFU0gnJ8wr8Egm8BGVO1LJiJ54MYQAABE=,iv:xDbXTyarlHMXcZxH/G8aoE/4rCiVRTtpxjdLHZtpdoQ=,tag:GGyo2slIFw3+rN+1FDH7Qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
